# Generated by Django 4.1.5 on 2023-01-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='proyectos',
            name='fecha_inicio',
        ),
    ]
