# Generated by Django 4.1.5 on 2023-01-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_rename_user_contacto_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='user_id',
            new_name='user',
        ),
    ]
