# Generated by Django 4.1.5 on 2023-01-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_proyectos_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='imagen',
            field=models.ImageField(blank=True, default='buscar.jpg', null=True, upload_to='proyectos'),
        ),
    ]
